#!/usr/bin/env bash

set -euo pipefail

VERSION_FILE="$1"
OUTPUT_DIR="$2"
FALLBACK_VERSION="0.0.1"

version="${FALLBACK_VERSION}"
if [[ -f "${VERSION_FILE}" ]]; then
	resolved="$(tr -d '[:space:]' < "${VERSION_FILE}")"
	if [[ -n "${resolved}" ]]; then
		version="${resolved}"
	fi
fi

escaped_version="${version//\\/\\\\}"
escaped_version="${escaped_version//\"/\\\"}"

mkdir -p "${OUTPUT_DIR}"
cat > "${OUTPUT_DIR}/QuickDevVersion.generated.swift" <<EOF
// Auto-generated by CLIVersionPlugin from VERSION.
// Do not edit manually.

let quickDevCLIVersion = "${escaped_version}"
EOF
